### ISSUE TITLE
执行了一个demo, 一直报404错误

### ISSUE THREAD

**Issue by chenweiyi** [web-infra-dev/midscene#183]
## 问题描述
我按照官方文档执行如下yaml:
```
target:
  url: https://www.baidu.com

tasks:
  - name: 搜索天气
    flow:
      - ai: 点击输入框， 输入 "今日天气"
      - sleep: 3000

  - name: 检查结果
    flow:
      - aiAssert: 结果中展示了天气信息
```

执行命令：`pnpm run test`

报如下错误：
![Image](https://github.com/user-attachments/assets/5200ae93-c87f-45b4-ae66-3d3304fa670e)
![Image](https://github.com/user-attachments/assets/912a35a1-5782-4fb8-8de1-66273598b970)

## 环境变量配置：
![Image](https://github.com/user-attachments/assets/d1981199-e131-4590-a737-b55e7da3f250)

## 期望

希望可以正常走完流程，打开百度，输入“今日天气“, 执行断言
