### ISSUE TITLE
[Bug]: when url is http, in yaml mode not support, it not work

### ISSUE THREAD

**Issue by liuestc** [web-infra-dev/midscene#707]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 78.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 134.1.76.74
    Chrome: 136.0.7103.93
    Safari: 17.6
  npmPackages:
    @midscene/cli: 0.16.10 => 0.16.8 
    @midscene/web: 0.16.8 => 0.16.8
```

### Details

when the website is http only , it sames not work

my yaml file is like 
```
target:
  url: http://httpforever.com/
  output: ./output/github-status.json
  acceptInsecureCerts: true
  waitForNetworkIdle:
    timeout: 8000
    continueOnNetworkIdleError: true
tasks:
  - name: test httponly
    flow:
      - aiAssert: 验证有「A reliably insecure connection」出现

```

when i use in yaml mode ,

<img width="1295" alt="Image" src="https://github.com/user-attachments/assets/9c28e956-c1c0-4b69-b1ed-4b496a1a5a00" />

### Reproduce link

**

### Reproduce Steps

```
midscene testCase/httponly.yaml
```
