### ISSUE TITLE
[Feature]: runYaml supports setting error_message for aiAssert.

### ISSUE THREAD

**Issue by tiancihe** [web-infra-dev/midscene#758]
### What problem does this feature solve?

runYaml 支持自定义 aiAssert 错误信息以便调试

### What does the proposed API look like?

```yaml
tasks:
  - name: test
    flow: 
      - aiAssert: xxx
        errorMessage: xxx
```
